// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	domain "go_service/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MembersRepository is an autogenerated mock type for the MembersRepository type
type MembersRepository struct {
	mock.Mock
}

// GetMemberData provides a mock function with given fields: organizationId
func (_m *MembersRepository) GetMemberData(organizationId string) ([]domain.Members, error) {
	ret := _m.Called(organizationId)

	var r0 []domain.Members
	if rf, ok := ret.Get(0).(func(string) []domain.Members); ok {
		r0 = rf(organizationId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Members)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(organizationId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type NewMembersRepositoryT interface {
	mock.TestingT
	Cleanup(func())
}

// NewMembersRepository creates a new instance of MembersRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMembersRepository(t NewMembersRepositoryT) *MembersRepository {
	mock := &MembersRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
